# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_comment_date_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_edited',
            field=models.DateTimeField(),
        ),
    ]
