# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
