# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_dateposted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug_field',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
