# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170502_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='parent',
        ),
    ]
